### PR TITLE
Subscribe

### LINKED ISSUE #10: Add email signup form to website
Have received several requests to add email signup on website

### PR DESCRIPTION
**Pull request by lucascolusso**
however, the transition is still not there, couldn't figure out today

after we do this, we can merge and close #10

### CODE REVIEW

**Comment by mahirk** [comment]
@lucascolusso whats the status on this?

**Comment by lucascolusso** [comment]
Can someone check the button color transition? That's the only thing I
couldn't figure out how to do.

--Lucas Colusso

PhD Student / Human Centered Design & Engineering
University of Washington
website <http://lucascolusso.github.io/personal_site/>

**Comment by mahirk** [comment]
@grant? If not I will merge this and look into it this weekend

**Comment by grant** [comment]
Please don't merge till you review it. The changes can't be in the build dir
Mahir Kothary <notifications@github.com>于2015年8月7日 周五15:43写道：

**Comment by mahirk** [comment]
@grant I've reviewed it, the changes in the build dir are what runs the actual site, so anychange he makes in the other pages, creates a change in the build dir which is what the `index.html` page loads

I'll pull that branch and run it as well

**Comment by grant** [comment]
@mahirk My bad; looked at the diff from my phone and it first showed the build dir changes. Merged. Will add the transition soon.

**Comment by grant** [comment]
Good work @lucascolusso.

**Comment by lucascolusso** [comment]
:facepunch:

sorry for not figuring out the transitions piece, except that, messing with react was a breeze :+1:

**Pull request merged**
